import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :proofie, ProofieWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :proofie, Proofie.Mailer,
  adapter: Proofie.EnveloopAdapter,
  api_key: System.get_env("ENVELOOP_LIVE_API_KEY"),
  template: System.get_env("ENVELOOP_TEMPLATE_ID")
